// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticate a user and issue auth tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.CredentialsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "description": "Rotate a refresh token and issue a new token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "description": "Refresh payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "description": "Create a user, provision a bucket, and issue auth tokens.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up",
                "parameters": [
                    {
                        "description": "Signup payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.CredentialsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List folders and files under the authenticated user's bucket path.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "List files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relative folder path",
                        "name": "path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Continuation token from previous page",
                        "name": "continuation_token",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max keys to request from S3-compatible storage",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.FileListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload a single file to a destination path in the user's bucket",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "File to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination path within bucket",
                        "name": "path",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Override filename",
                        "name": "filename",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.FileUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload-folder": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload multiple files to a destination folder in the user's bucket, preserving relative paths",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload folder",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Files to upload (repeated)",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Relative path for each file (repeated, must match files count)",
                        "name": "relative_paths",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination folder path within bucket",
                        "name": "path",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.FolderUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload-multipart/abort": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Abort an in-flight multipart upload and clean up uploaded parts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Abort multipart upload",
                "parameters": [
                    {
                        "description": "Multipart abort payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadAbortRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload-multipart/complete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Complete an S3 multipart upload after all parts are uploaded",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Complete multipart upload",
                "parameters": [
                    {
                        "description": "Multipart complete payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadCompleteRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.FileUploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload-multipart/initiate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Start an S3 multipart upload for a file larger than 5 MB via the backend",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Initiate multipart upload",
                "parameters": [
                    {
                        "description": "Multipart upload payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadInitiateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadInitiateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/files/upload-multipart/part": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload one multipart chunk through the backend into object storage",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Upload multipart chunk",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Multipart upload id",
                        "name": "upload_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Final object key",
                        "name": "key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Part number",
                        "name": "part_number",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Multipart chunk payload",
                        "name": "part",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadPartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Return the authenticated user from the access token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.AuthenticatedUser"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_abhishek_pen-drive_backend_internal_api_dto.AuthResponse": {
            "type": "object",
            "properties": {
                "tokens": {
                    "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.TokenPair"
                },
                "user": {
                    "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.AuthenticatedUser"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.AuthenticatedUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "01kki6wb2vqqw4x63mw9bjw6y4"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.CredentialsRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "Password123!"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorPayload": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "invalid_request"
                },
                "message": {
                    "type": "string",
                    "example": "request body is invalid"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.ErrorPayload"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.FileListResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.FileSystemEntry"
                    }
                },
                "has_more": {
                    "type": "boolean",
                    "example": false
                },
                "next_continuation_token": {
                    "type": "string",
                    "example": "token-123"
                },
                "path": {
                    "type": "string",
                    "example": "docs"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.FileSystemEntry": {
            "type": "object",
            "properties": {
                "last_modified": {
                    "type": "string",
                    "example": "2026-03-12T16:00:00Z"
                },
                "name": {
                    "type": "string",
                    "example": "photo.jpg"
                },
                "path": {
                    "type": "string",
                    "example": "photos/photo.jpg"
                },
                "size": {
                    "type": "integer",
                    "example": 2048
                },
                "type": {
                    "type": "string",
                    "example": "file"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.FileUploadResponse": {
            "type": "object",
            "properties": {
                "file": {
                    "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.UploadedFileInfo"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.FolderUploadResponse": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.UploadedFileInfo"
                    }
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartCompletedPart": {
            "type": "object",
            "properties": {
                "etag": {
                    "type": "string",
                    "example": "\"etag-value\""
                },
                "part_number": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadAbortRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "uploads/videos/video.mp4"
                },
                "upload_id": {
                    "type": "string",
                    "example": "upload-id"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadCompleteRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "uploads/videos/video.mp4"
                },
                "parts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartCompletedPart"
                    }
                },
                "upload_id": {
                    "type": "string",
                    "example": "upload-id"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadInitiateRequest": {
            "type": "object",
            "properties": {
                "content_type": {
                    "type": "string",
                    "example": "video/mp4"
                },
                "filename": {
                    "type": "string",
                    "example": "video.mp4"
                },
                "path": {
                    "type": "string",
                    "example": "uploads/videos"
                },
                "size": {
                    "type": "integer",
                    "example": 7340032
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadInitiateResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "uploads/videos/video.mp4"
                },
                "name": {
                    "type": "string",
                    "example": "video.mp4"
                },
                "part_size": {
                    "type": "integer",
                    "example": 5242880
                },
                "upload_id": {
                    "type": "string",
                    "example": "upload-id"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.MultipartUploadPartResponse": {
            "type": "object",
            "properties": {
                "etag": {
                    "type": "string",
                    "example": "\"etag-value\""
                },
                "part_number": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.RefreshRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string",
                    "example": "refresh-token"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.TokenPair": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiJ9"
                },
                "access_token_expires_at": {
                    "type": "string",
                    "example": "2026-03-12T16:00:00Z"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "opaque-refresh-token"
                },
                "refresh_token_expires_at": {
                    "type": "string",
                    "example": "2026-04-11T16:00:00Z"
                }
            }
        },
        "github_com_abhishek_pen-drive_backend_internal_api_dto.UploadedFileInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "document.pdf"
                },
                "path": {
                    "type": "string",
                    "example": "uploads/document.pdf"
                },
                "size": {
                    "type": "integer",
                    "example": 1024576
                },
                "uploaded_at": {
                    "type": "string",
                    "example": "2026-03-12T16:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "pen-drive API",
	Description:      "pen-drive backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
